### PR TITLE
Replace deprecated method usage

### PR DESCRIPTION
**Pull request by PikachuEXE**
`URI.escape` is obsoleted: https://github.com/ruby/ruby/commit/238b979f1789f95262a267d8df6239806f2859cc

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Will be ready for review once #116 merged, since this is based on that PR
I want to rebase before marking this PR as ready anyway

**Comment by PikachuEXE** [comment]
Screw it, I rebased on master without changes in #116 :D

**Comment by PikachuEXE** [comment]
I am not sure if we should use `URI::Parser#escape` instead which is available in `1.9`
https://github.com/sinatra/sinatra-contrib/pull/127

**Comment by PikachuEXE** [comment]
Rebased on latest `master` and test passed

**Comment by sdsykes** [comment]
Thanks I'll look at this, and aim to make a release shortly.

**Comment by PikachuEXE** [comment]
Reminder to look at this PR~

**Comment by PikachuEXE** [comment]
On vacation?

**Comment by sdsykes** [comment]
For another week!

**Comment by PikachuEXE** [comment]
Have a good one!

**Comment by sdsykes** [comment]
These are not the same?

```
irb(main):003:0> ERB::Util.url_encode("/pho to.gne?rb=1&short=Vv4Und")
=> "%2Fpho%20to.gne%3Frb%3D1%26short%3DVv4Und"
irb(main):004:0> URI.escape("/pho to.gne?rb=1&short=Vv4Und")
=> "/pho%20to.gne?rb=1&short=Vv4Und"
```

**Comment by PikachuEXE** [comment]
Forgot to test with `erb` required
Anyway updated to use `URI::DEFAULT_PARSER` as there is already a patch for old rubies

**Comment by PikachuEXE** [comment]
Build passed
image

Any chance we can see the CI check status in future PR without manually checking it?

**Comment by PikachuEXE** [comment]
Hope to see a new release soon~

**Comment by PikachuEXE** [comment]
Will there be a new release this or next week?

**Comment by sdsykes** [comment]
I released it already....

**Comment by PikachuEXE** [comment]
Sorry
Forgot watch for new releases
And my gemfile is pointing to specific commit

**Pull request merged**
