### PR TITLE
Use GitHub Actions for CI

### PR DESCRIPTION
**Pull request by orien**
travis-ci.org is dead. I propose the use of GitHub Actions to run the test suite in CI.

### CODE REVIEW

**Comment by sdsykes** [comment]
Seems like a good idea!

**Comment by sdsykes** [comment]
Why is it reporting "Workflow runs completed with no jobs" though?

**Comment by orien** [comment]
🤔 Great question.

The build has run successfully in my fork of the repo: https://github.com/orien/fastimage/actions/runs/3929983734

I think only after the PR is merged will it work for the `sdsykes/fastimage` repo

This is probably a security feature.

**Comment by sdsykes** [comment]
Ok let's merge.

**Pull request merged**
