### PR TITLE
Fix for SVG with XML preamble

### PR DESCRIPTION
**Pull request by johnshearar**
We often deal with SVGs that contain `<!DOCTYPE` tags which push the start of the `<svg` tag beyond the type parsing lookahead of 100 bytes. I've extended the lookahead as far as possible so that the existing tests pass.

### CODE REVIEW

**Comment by sdsykes** [comment]
Yeh, it looks like there is a problem that should really be fixed in peek (as you found).

Also you can remove the addressable fix, I removed that gem just now anyway.

**Comment by sdsykes** [comment]
Suggest this https://github.com/sdsykes/fastimage/commit/bd150b54afedce3362226600c249f74de30a2291

**Comment by schmidt** [comment]
I've been looking at SVG detection previously and I had to realize, that the peeking at `<svg` is a 'best effort' approach at best. 

I can easily create valid files, which would be detected as svg, but they are not. Here would be just two examples:

An HTML file containing an svg.
```html
<!DOCTYPE html>
<html>
<body>

<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>

</body>
</html>
```

Any XML file containing *interesting* comments
```
<?xml version="1.0"?>
<!-- This is not an <svg> -->
<note>
  <to>Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```

And we can have totally valid `svg` files, which are not properly detected, e.g. when they are encoded in UTF-16. (<--- This is a 80 % guess. I think, I've investigated that but I cannot exactly remember what the outcome was.)

I assume it's similar with the other file types - but since they are binary it's not as apparent.

What I'm trying to say is: I think peeking a bit further is good enough. By looking at the whole file, we'll probably not improve accuracy much.

**Comment by johnshearar** [comment]
> Suggest this bd150b5

Looks good to me! I'm happy if you close this PR in favour of that implementation :)

**Comment by sdsykes** [comment]
@schmidt yes, agree. fastimage is not particularly doing any validation on other formats either, but svg is particularly problematic.
@johnshearar yes, thanks, I'll do that I think, appreciate your input.

**Pull request closed without merging**
