### PR TITLE
Data URIs scheme handling

### PR DESCRIPTION
**Pull request by jschwindt**
I had some time today and created this PR to handle [Data URIs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) as commented before in #74.

Let me know what do you think about it. The comparison across for forks is longer than expected because my editor removed some trailing spaces.

### CODE REVIEW

**Comment by sdsykes** [comment]
Hm, the CI fails on 1.9.x - but I don't immediately see how the problem is related, can you check?

**Comment by jschwindt** [comment]
Gem::InstallError: public_suffix requires Ruby version >= 2.0.

public_suffix is a dependency of addressable gem.

**Comment by sdsykes** [comment]
Ah ok. I need to look into that then. Thanks.

**Comment by sdsykes** [comment]
Thanks for this, and sorry for the delay in processing. I'll make a new release once I've merged the other PRs I have. By the way, I realise that github's resolve conflicts workflow committed directly into your fork, which I fear might be a tad rude, sorry for that.

**Pull request merged**
