### PR TITLE
Add support for SVG

### PR DESCRIPTION
**Pull request by kikihakiem**
[Review on Reviewable](https://reviewable.io/reviews/sdsykes/fastimage/50)

### CODE REVIEW

**Comment by kikihakiem** [comment]
@sdsykes I just realized that it's possible that an SVG image has [viewBox](http://www.w3.org/TR/SVG/coords.html#ViewBoxAttribute) attribute and either width or height only. I will update this PR to handle those case.

**Comment by sdsykes** [comment]
Ok!

**Comment by kikihakiem** [comment]
@sdsykes I was trying to add support for SVGZ, but I'm stuck at reading gz stream ("dead fiber called" error). I think we can just go with SVG support only for now.
Could you please review?

**Comment by sdsykes** [comment]
Nice thanks - agree about svgz. My comments:

I'm not sure I want to break out the svg size parser to a new file. Yes, fastimage is 600 lines... so adding the svg stuff won't increase it that much :) If we do svg in a separate file, then probably other ones like jpeg, exif stuff etc could be split out. But that (I mean spitting in general) is a separate decision

Also I think that StreamUtil should gain a method read_string_int which would do what attr_value does.

**Comment by kikihakiem** [comment]
@sdsykes thank you for the review. Did you mean `read_int`? I tried but it gave me different result and the test failing. Any idea?

**Comment by sdsykes** [comment]
I meant you could make a new method in StreamUtil that would be called read_string_int that would do exactly what attr_value does (meaning it would an int from the string). It's different from read_int which reads a binary value.

**Comment by kikihakiem** [comment]
@sdsykes I'm sorry. English is not my native language, so I'm confused.
Wondering if I can use `read_string_int` for reading viewbox value, but apparently I can't. Because whitespace character between the integer could be more than 1. Could you please review?

**Comment by sdsykes** [comment]
That looks like what I meant, I guess it ended up being a bit more code my way, but anyway I think I can merge this.

**Pull request merged**
