### PR TITLE
Identify svg files that start with white spaces

### PR DESCRIPTION
**Pull request by delphaber**
Hi :)

sometimes svg files, being text files, can contain leading white spaces. I created this small PR to correctly identify these svg images too.

Hope this helps!

### CODE REVIEW

**Comment by sdsykes** [comment]
Is there any specific reason to also check the first 1000 chars rather than the first 250? (Are you seeing that much whitespace at the beginning of svg files?)

**Comment by delphaber** [comment]
Perhaps we wanted to be (too) cautious 😅 Will you consider this PR if we reset the original 250 chars?

**Comment by sdsykes** [comment]
Sure!

**Comment by delphaber** [comment]
@sdsykes done! :)

**Comment by delphaber** [comment]
thanks for merging! <3

**Pull request merged**
