### PR TITLE
Make dependency on addressable optional

### PR DESCRIPTION
**Pull request by SamSaffron**
Make dependency on addressable optional, allow consumers to easily pick a uri parser

### CODE REVIEW

**Comment by sdsykes** [comment]
I think I'm against making a breaking change where anyone running 2.1 or below will get the underscore parsing issue back. (2.2.0 is only 1.5 months old at this point).

Would it be better to make the chosen parser depend on RUBY_VERSION? (Or maybe if URI.constants.include?(:RFC2396_Parser) or something more relevant?)

**Comment by SamSaffron** [comment]
This is a tough problem, thing is we don't use any of the HTTP stuff at Discourse, we are always passing fastimage files not uris. 

The dependency story is tricky. cause splitting this into 2 gems may feel a bit like an overkill. I am not sure what the best approach here is. 

A simple approach could be to automatically include Addressable if the constant is defined and then just remove the dependency from the gem?

**Comment by sdsykes** [comment]
Hi Sam,

>A simple approach could be to automatically include Addressable if the constant is defined and then just remove the dependency from the gem?

I don't know, maybe this can break ruby pre 2.2 users if they run bundle against the new gem?

Here's an idea - as it's effectively a breaking change, how about we do just what you suggest, and bump the major version number? So make it 2.0.0, and note that you should make sure your bundle includes Addressable if you are using earlier rubies?

BTW, I think allowing the user to inject a particular URI parser is overkill, I'd be happier to leave that mod out.

You want to submit a PR along these lines?

**Comment by SamSaffron** [comment]
I am still struggling with this, the thing is that the gem is providing 2 functions. At the moment we are using none of the URI stuff as all the files we have that we are measuring are local, so pulling in an extra gem seems superflous. I wonder if we should look to split this into 2 classes so one is responsible for the sizing stuff and another for the fetching stuff. 

The dependency story is tricky because there is no way of adding a "provisional" dependency in the gemfile

Happy to remove some of the extra extensibility stuff in the PR, but if we are doing a 2.0 it may make more sense to split it up first.

**Comment by guilhermesimoes** [comment]
Apparently open-uri is not safe: http://sakurity.com/blog/2015/02/28/openuri.html

**Comment by sdsykes** [comment]
Thanks. FastImage is affected, I will patch asap.

**Comment by schmidt** [comment]
Since we were facing a similar problem - we did not need remote image support and it felt like an unnecessary attack vector. So we created a stripped down version of fastimage named [local-fastimage](https://github.com/planio-gmbh/local-fastimage). Maybe that's interesting for you.

We plan to keep it compatible with fastimage - though version numbers will probably differ.

**Comment by sdsykes** [comment]
Resolved (eventually) by removing addressable.

**Comment by SamSaffron** [comment]
yay!

**Pull request closed without merging**
